# -*- coding: utf-8 -*-
"""Copy of carnumberdetect.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17zA_lQVPdI1gq8CXQtC4Jkoa-Q9Bbesu
"""

!pip install easyocr
!pip install imutils
!pip install pydub

import cv2
from matplotlib import pyplot as plt
import numpy as np
import imutils
import easyocr
from datetime import date
import pandas as pd
from datetime import datetime
from pydub import AudioSegment
from pydub.playback import play

img = cv2.imread('image1.jpg')
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
plt.imshow(cv2.cvtColor(gray, cv2.COLOR_BGR2RGB))

bfilter = cv2.bilateralFilter(gray, 11, 17, 17) #Noise reduction
edged = cv2.Canny(bfilter, 30, 200) #Edge detection
plt.imshow(cv2.cvtColor(edged, cv2.COLOR_BGR2RGB))

keypoints = cv2.findContours(edged.copy(), cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
contours = imutils.grab_contours(keypoints)
contours = sorted(contours, key=cv2.contourArea, reverse=True)[:10]

location = None
for contour in contours:
    approx = cv2.approxPolyDP(contour, 10, True)
    if len(approx) == 4:
        location = approx
        break

location

mask = np.zeros(gray.shape, np.uint8)
new_image = cv2.drawContours(mask, [location], 0,255, -1)
new_image = cv2.bitwise_and(img, img, mask=mask)

plt.imshow(cv2.cvtColor(new_image, cv2.COLOR_BGR2RGB))

plt.imshow(cv2.cvtColor(new_image, cv2.COLOR_BGR2RGB))

(x,y) = np.where(mask==255)
(x1, y1) = (np.min(x), np.min(y))
(x2, y2) = (np.max(x), np.max(y))
cropped_image = gray[x1:x2+1, y1:y2+1]

plt.imshow(cv2.cvtColor(cropped_image, cv2.COLOR_BGR2RGB))

reader = easyocr.Reader(['en'])
result = reader.readtext(cropped_image)
result
# from datetime import datetime

# now = datetime.now()

# current_time = now.strftime("%H:%M:%S"
def getdate():
    now = date.today()
    return now.strftime("%d/%m/%Y ")
def gettime():
    n= datetime.now()

    return n.strftime("%H:%M:%S")



# import pandas as pd
data=pd.read_csv("entry.csv")
data.head()

test=result[0][-2]
print(test)
list1=[]
list2=[]
list3=[]

# data.insert(1,"data_time",gettime())
# data.insert(1,"car_plate",test)
# data.insert(2,"data_time1",gettime())
# data.head()
# with open ("date-time1.txt","a") as f:
#       f.write(str([str(gettime())]) + ":" + test + "\n")

song = AudioSegment.from_mp3("note.mp3")
# print('playing sound using  pydub')
# play(song)
list1.append(test)
list2.append(getdate())
list3.append(gettime())
df = pd.DataFrame(list(zip(list1, list2,list3)),
               columns =['numer', 'date','time'])
df

# df.to_csv('saved.csv')

number=(data["name"]).to_list()
print(number)

if list1 in number:

  df = pd.DataFrame(list(zip(list1, list2,list3)),
               columns =['numer', 'date','time'])

else:
  df1 = pd.DataFrame(list(zip(list1)),
               columns =['number2'])

  print("ping the alarm")
  play(song)
df

df1

